name: Ubuntu Bionic CI

on: [push, pull_request]

jobs:
  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Bionic CI
        id: ci
        uses: ignition-tooling/ubuntu-bionic-ci-action@master
        with:
          apt-dependencies: 'pkg-config libcurl4-openssl-dev libjsoncpp-dev libzip-dev libgflags-dev libtinyxml2-dev lcov curl libyaml-dev libignition-cmake2-dev libignition-common3-dev libignition-math6-dev libignition-msgs5-dev'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          script-after-make: ../.github/ci-bionic/after_make.sh
